version: '3.7'

services:
  sonarqube:
    image: sonarqube    
    ports:    
      - 9000:9000
    volumes:
      - /sonarqubeserver/sonarqube/data:/opt/sonarqube/data \
      - /sonarqubeserver/sonarqube/extensions:/opt/sonarqube/extensions \

 # nexus:
 #   image: sonatype/nexus3
 #   ports:
 #     - 8081:8081    